### ISSUE TITLE
java.lang.IllegalStateException when destroying Bean that is a mock of a repository

### ISSUE THREAD

**Issue by BenoitAverty** [mmnaseri/spring-data-mock#12]
I am using spring to inject a mock created with this project into a context. Here is the configuration class:

```
@Configuration
@Import(OrderApplication.class)
@ComponentScan("com.example.unit.testing.domain")
class OrderApplicationTestContext {
	
	@Bean
	OrderRepository orderRepository() {
		return builder()
				.generateKeysUsing(RandomLongKeyGenerator.class)
				.mock(OrderRepository.class);
	}
	
	@Bean
	CustomerRepository customerRepository() {
		return builder()
				.generateKeysUsing(RandomLongKeyGenerator.class)
				.mock(CustomerRepository.class);
	}
	
}
```

It works fine and my test pass. However, when this spring context is destroyed, an exception is thrown by the destroyMethod:

```
2016-04-08 13:47:56.015 ERROR 23753 --- [       Thread-1] o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'orderRepository' threw an exception

java.lang.IllegalStateException: No operation mapping found for method public native int java.lang.Object.hashCode()
	at com.mmnaseri.utils.spring.data.proxy.impl.DataOperationInvocationHandler.invoke(DataOperationInvocationHandler.java:56) ~[spring-data-mock-1.0.jar:na]
	at com.sun.proxy.$Proxy27.hashCode(Unknown Source) ~[na:na]
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) ~[na:1.8.0_77]
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) ~[na:1.8.0_77]
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessBeforeDestruction(PersistenceAnnotationBeanPostProcessor.java:374) ~[spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:243) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:972) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:979) [spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1006) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:982) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:901) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
```

Do you know what might be causing this ?

**Comment by BenoitAverty** [comment]
I investigated this a bit. The problem seems to be that the `hashCode()` method is not available through proxies created with `builder().mock(...)`. I'm not familiar enough with proxies and reflection in Java but I think the proxy shouldn't throw an exception when no mapping is found for `Object....` methods (at least equals and hashCode), but just call the real methods in that case.

**Comment by mmnaseri** [comment]
I think thanks to @Kaidjin this can be marked as resolved, now. I will close the issue once I release the code to Maven Central.

**Comment by mmnaseri** [comment]
You can now find a working version at `com.mmnaseri.utils:spring-data-mock:1.0.1`
