### ISSUE TITLE
NoClassDefFoundError error

### ISSUE THREAD

**Issue by omri-shaiko** [mmnaseri/spring-data-mock#146]
Hi,

I'm trying to implement this for my unit tests.
I'm using Spock and spring 1.4.3

This line:
`builder().mock(AccountRepository.class) `
Causing the following exception:

`java.lang.NoClassDefFoundError: com/querydsl/core/alias/Alias

	at com.mmnaseri.utils.spring.data.repository.DefaultQueryDslPredicateExecutor.setDataStore(DefaultQueryDslPredicateExecutor.java:60)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getTypeMappings(DefaultRepositoryFactory.java:137)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getInstance(DefaultRepositoryFactory.java:69)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:103)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:101)
	at com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder.mock(RepositoryFactoryBuilder.java:273)
	at contoller.adminAccountController.CreateAccountSpec.setup(CreateAccountSpec.groovy:46)
`
`Caused by: java.lang.ClassNotFoundException: com.querydsl.core.alias.Alias
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more`

Any idea why?

**Comment by mmnaseri** [comment]
This seems to indicate that the QueryDSL package in your classpath is the wrong (incompatible) version. Would you mind sharing your project's setup (dependencies) so that I can replicate?

**Comment by mmnaseri** [comment]
Closing due to lack of feedback, and also because Querydsl is now unsupported as of 2.0.0.
