### ISSUE TITLE
Fix the issue where JPA annotations aren't honored

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#55]
Unit test below fails

```
com.mmnaseri.utils.spring.data.error.NoIdPropertyException: No id property could be resolved for type class com.bee2c.platform.entity.FbpMbpPolicy
	at com.mmnaseri.utils.spring.data.domain.impl.id.EntityIdPropertyResolver.resolve(EntityIdPropertyResolver.java:55)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolveIdProperty(AbstractRepositoryMetadataResolver.java:69)
	at com.mmnaseri.utils.spring.data.domain.impl.AssignableRepositoryMetadataResolver.resolveFromInterface(AssignableRepositoryMetadataResolver.java:29)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolve(AbstractRepositoryMetadataResolver.java:49)
	at com.mmnaseri.utils.spring.data.domain.impl.DefaultRepositoryMetadataResolver.resolveFromInterface(DefaultRepositoryMetadataResolver.java:34)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolve(AbstractRepositoryMetadataResolver.java:49)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:97)
	at com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder.mock(RepositoryFactoryBuilder.java:273)
	at com.bee2c.platform.MbpDatabaseRelationsTest.testDemo(MbpDatabaseRelationsTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Entity
```java
@Entity
@Table(name = "fbp_mbp_policy")
public class FbpMbpPolicy extends BaseEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "mbp_policy_id")
	private Long mbpPolicyId;
```

```java
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.bee2c.platform.entity.FbpMbpPolicy;
import com.bee2c.platform.entity.FbpMbpPolicyDate;
import com.bee2c.platform.repository.FbpMbpPolicyDateRepository;
import com.bee2c.platform.repository.FbpMbpPolicyRepository;

import com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder;

public class MbpDatabaseRelationsTest {
	
	private static final Logger log = LoggerFactory.getLogger(MbpDatabaseRelationsTest.class);


	@Test
	public void testDemo() {
		
		final FbpMbpPolicyRepository repository = RepositoryFactoryBuilder.builder().mock(FbpMbpPolicyRepository.class);
		final FbpMbpPolicyDateRepository policyDateRepository = RepositoryFactoryBuilder.builder().mock(FbpMbpPolicyDateRepository.class);

		FbpMbpPolicy policy = new FbpMbpPolicy();
		repository.save(policy);
		log.info(policy.toString());
		
		FbpMbpPolicyDate policyDate = new FbpMbpPolicyDate();
		policyDate.setMbpPolicy(policy);
		policyDateRepository.save(policyDate);
		log.info(policyDate.toString());

		FbpMbpPolicyDate policyDate2 = new FbpMbpPolicyDate();
		policyDate2.setMbpPolicy(policy);
		policyDateRepository.save(policyDate2);
		log.info(policyDate2.toString());
		
		
	}

}
```

**Comment by paulvi** [comment]
AnnotatedFieldIdPropertyResolver  is using @`org.springframework.data.annotation.Id`
while code uses @`javax.persistence.Id`

```java
import com.mmnaseri.utils.spring.data.domain.IdPropertyResolver;
import com.mmnaseri.utils.spring.data.error.MultipleIdPropertiesException;
import com.mmnaseri.utils.spring.data.error.PropertyTypeMismatchException;
import org.springframework.data.annotation.Id;
import org.springframework.util.ReflectionUtils;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.concurrent.atomic.AtomicReference;

/**
 * This class will help resolve ID property name if the entity has a field that is annotated with
 * {@link Id @Id}
 *
 * @author Milad Naseri (mmnaseri@programmer.net)
 * @since 1.0 (9/23/15)
 */
@SuppressWarnings("WeakerAccess")
public class AnnotatedFieldIdPropertyResolver implements IdPropertyResolver {

    @Override
    public String resolve(final Class<?> entityType, Class<? extends Serializable> idType) {
        final AtomicReference<Field> found = new AtomicReference<>();
        //try to find the ID field
        ReflectionUtils.doWithFields(entityType, new ReflectionUtils.FieldCallback() {
            @Override
            public void doWith(Field field) throws IllegalArgumentException, IllegalAccessException {
                if (field.isAnnotationPresent(Id.class)) {

```

**Comment by paulvi** [comment]
well, I added getter, but ran into next problem

```
	// for spring-data-mock https://github.com/mmnaseri/spring-data-mock/issues/55
	public Long getId() {
		return mbpPolicyId;
	}
```

**Comment by mmnaseri** [comment]
I'm going to address this with a fix momentarily. I'm just gonna add a regression test first.

**Comment by paulvi** [comment]
Milad, I am just giving a first try. The real stopper for me is #56
