### ISSUE TITLE
Add support for querying entities by example

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#56]
```java
com.mmnaseri.utils.spring.data.error.DataOperationDefinitionException: Encountered an error while resolving operation metadata: public abstract java.util.List com.bee2c.platform.repository.FbpMbpPolicyRepositoryCustom.findByExample(com.bee2c.platform.entity.FbpMbpPolicy)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.DefaultDataOperationResolver.resolve(DefaultDataOperationResolver.java:45)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getInvocationMappings(DefaultRepositoryFactory.java:210)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getInstance(DefaultRepositoryFactory.java:76)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:103)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:101)
	at com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder.mock(RepositoryFactoryBuilder.java:273)
	at com.bee2c.platform.MbpDatabaseRelationsTest.testDemo(MbpDatabaseRelationsTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.mmnaseri.utils.spring.data.error.QueryParserException: interface com.bee2c.platform.repository.FbpMbpPolicyRepositoryCustom: Could not find property `example` on `class com.bee2c.platform.entity.FbpMbpPolicy`
	at com.mmnaseri.utils.spring.data.domain.impl.QueryDescriptionExtractor.getPropertyDescriptor(QueryDescriptionExtractor.java:263)
	at com.mmnaseri.utils.spring.data.domain.impl.QueryDescriptionExtractor.parseExpression(QueryDescriptionExtractor.java:205)
	at com.mmnaseri.utils.spring.data.domain.impl.QueryDescriptionExtractor.extract(QueryDescriptionExtractor.java:133)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.QueryMethodDataOperationResolver.resolve(QueryMethodDataOperationResolver.java:53)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.DefaultDataOperationResolver.resolve(DefaultDataOperationResolver.java:43)
	... 29 more
Caused by: java.lang.IllegalStateException: Could not find property `example` on `class com.bee2c.platform.entity.FbpMbpPolicy`
	at com.mmnaseri.utils.spring.data.tools.PropertyUtils.getPropertyDescriptor(PropertyUtils.java:217)
	at com.mmnaseri.utils.spring.data.domain.impl.QueryDescriptionExtractor.getPropertyDescriptor(QueryDescriptionExtractor.java:261)
	... 33 more

```

and related code

```java
public interface FbpMbpPolicyRepository extends JpaRepository<FbpMbpPolicy, Long>,
	FbpMbpPolicyRepositoryCustom {
}

public interface FbpMbpPolicyRepositoryCustom {
	
	public List<FbpMbpPolicy> findByExample(FbpMbpPolicy probe);
	
	public Page<FbpMbpPolicy> findByExample(FbpMbpPolicy probe, Pageable pageable);
	
	public Page<FbpMbpPolicy> findByAnyExample(FbpMbpPolicy probe, Pageable pageable);

}

public class FbpMbpPolicyRepositoryImpl implements FbpMbpPolicyRepositoryCustom {
	
	@Autowired
	FbpMbpPolicyRepository repository;

	@Override
	public List<FbpMbpPolicy> findByExample(FbpMbpPolicy probe) {
		return repository.findAll(Example.of(probe));
	}

	@Override // see QueryByExampleExecutor
	public Page<FbpMbpPolicy> findByExample(FbpMbpPolicy probe, Pageable pageable) {
		return repository.findAll(Example.of(probe),pageable);
	}

    ...

```

**Comment by paulvi** [comment]
See docs

- http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.single-repository-behaviour
- http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example

**Comment by mmnaseri** [comment]
I see. So, I need to add support for querying by example. This will take more than a couple minutes. But I'm on it nonetheless.

**Comment by mmnaseri** [comment]
I think this will be easy to do (the same way I have added support for QueryDsl)

**Comment by paulvi** [comment]
Nice to hear about you being optimistic.

Do you mean that repositories that `extends QueryDslPredicateExecutor` are already supported?

**Comment by mmnaseri** [comment]
Yep. I did it as part of #3 though it is still pending verification by the original requester, since I don't usually use `QueryDslPredicateExecutor` myself.

It is in the `development` branch, but I haven't released it yet.

You should be able to clone the `development` branch, install it locally and use it for now. I think I will either do a separate release for that feature or bundle the new ones you have opened up with that and release it all as **1.1**.

**Comment by paulvi** [comment]
I have to say, I don't plan to clone/work on code. Just quick feedback, and try again when released.
I need to give a tool to developers, and those developers are unlikely to ever raise an issue :-(

**Comment by mmnaseri** [comment]
That's alright. I think I will be able to push the release to happen by tomorrow night. Is that good enough?

**Comment by mmnaseri** [comment]
I can see that this one had escaped me since `QueryByExampleExecutor` was added to `JpaRepository` in `1.12`. I will fix this by implementing the proper methods in `com.mmnaseri.utils.spring.data.repository.DefaultJpaRepository`.

**Comment by paulvi** [comment]
>  Is that good enough?

Awesome. I can only tell around if you see any bug, it may be fixed within day. :+1:

**Comment by mmnaseri** [comment]
Great. I will start working on it tomorrow then. I will need some sleep 😁

**Comment by mmnaseri** [comment]
This should be possible now, as there is support for all the methods introduced in `org.springframework.data.repository.query.QueryByExampleExecutor`

**Comment by mmnaseri** [comment]
This is implemented and tested. I added an optional implementation for `org.springframework.data.repository.query.QueryByExampleExecutor` which takes care of this business. It does so by converting the matchers from Spring Data to query operations as defined by this framework, then does the rest like other select handlers by querying the data store.
