### ISSUE TITLE
Framework fails to associate primitive ID types -> use Long (not long)

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#83]
simplest sample No 1 (#82) `CustomerRepositoryTest` fails 

```
com.mmnaseri.utils.spring.data.error.PropertyTypeMismatchException: Expected property <id> of class <class hello.Customer> to be of type <class java.lang.Long> but it was of type <long>
	at com.mmnaseri.utils.spring.data.domain.impl.id.AnnotatedFieldIdPropertyResolver.resolve(AnnotatedFieldIdPropertyResolver.java:45)
	at com.mmnaseri.utils.spring.data.domain.impl.id.EntityIdPropertyResolver.resolve(EntityIdPropertyResolver.java:43)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolveIdProperty(AbstractRepositoryMetadataResolver.java:69)
	at com.mmnaseri.utils.spring.data.domain.impl.AssignableRepositoryMetadataResolver.resolveFromInterface(AssignableRepositoryMetadataResolver.java:29)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolve(AbstractRepositoryMetadataResolver.java:49)
	at com.mmnaseri.utils.spring.data.domain.impl.DefaultRepositoryMetadataResolver.resolveFromInterface(DefaultRepositoryMetadataResolver.java:34)
	at com.mmnaseri.utils.spring.data.domain.impl.AbstractRepositoryMetadataResolver.resolve(AbstractRepositoryMetadataResolver.java:49)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:97)
	at com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder.mock(RepositoryFactoryBuilder.java:273)
	at hello.CustomerRepositoryTest.testDemo(CustomerRepositoryTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:670)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by mmnaseri** [comment]
This is failing because there is no way to make sure the ID property is new or not with primitive types. With object wrappers it is easy to find out by simply doing a null-check, whereas with primitive types yo simply have no way of knowing if the ID property is set intentionally or if a value of `0L` of type `long` indicates that the data is raw.

This will be fixed with migrating the ID property type to `java.lang.Long`, and this framework is not the only one that struggles with this issue. Spring Data and Hibernate both have the same problem. You can just Google "Spring Data and primitive ID type" to see examples.

I could write a proxy wrapper for all entities that would do dirty-checking on the ID property to make sure that a pristine ID value (even if not `null`) indicates a new entity, but I think that would be too much work for little gain.

**Comment by paulvi** [comment]
I understand, each primitive type may need special handling.
Nevertheless, this is example from https://spring.io/guides/gs/accessing-data-jpa/ , new user can expect `private long id;` to work.

**Comment by mmnaseri** [comment]
I will have to think about a way to make this happen without too much change or boilerplate code.

Here are the different ways that pop into my head at the moment:

  1. Proxy saved entities. Un-proxied items are assumed to be new unless they have a key that matches an existing entity. Problem: breaks referential integrity.

  2. Write an `IsNew` handler for each primitive type. Problem: isn't bullet-proof, as an entity with `0L` might be legitimately stored in the data store at which point update and insert requests cannot be distinguished.

**Comment by mmnaseri** [comment]
As of  [v1.1.2](https://github.com/mmnaseri/spring-data-mock/tree/v.1.1.2) this is handled by throwing an exception whenever a primitive ID type is encountered, thus allowing for the user to recover without having to look around for the reason.

I will be looking for better alternatives in the meanwhile.

**Comment by mmnaseri** [comment]
Upon further deliberation, I have decided that it makes no sense to implement any sort of support for handling primitive ID types. Even though the Spring documentation clearly uses a primitive ID type, I would rather consider that they are mistaken in their example than that it is okay to write a lot of unnecessary logic to advocate a malpractice that should be clearly denounced.

**Comment by paulvi** [comment]
Yes, that was decision, but the issues should be closed with updated docs (e.g. README or site)

Most small open source project just keep such issues open.

**Comment by mmnaseri** [comment]
I have updated the documents with this decision: https://mmnaseri.github.io/spring-data-mock/site/#/readme#primitve-ids
