### ISSUE TITLE
1.1.1 Problem java.lang.AssertionError: saved entity can't be retrieved

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#84]
```
java.lang.AssertionError: saved entity can't be retrieved
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at hello.CustomerRepository2ndTest.savedEntitiesCanBeRetrieved(CustomerRepository2ndTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:670)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

code for #82 sample

```java
package hello;

import org.junit.Test;

import com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder;

import static org.junit.Assert.assertTrue;

public class CustomerRepository2ndTest {

    @Test
    public void savedEntitiesCanBeRetrieved() {

        final CustomerRepository repository = RepositoryFactoryBuilder.builder().mock(CustomerRepository.class);
        repository.save(new Customer());
        
        Customer c = repository.findOne(1L);
        assertTrue("saved entity can't be retrieved", c!=null);
    }
    
}
```

**Comment by mmnaseri** [comment]
This test case makes the assumption that ID generation starts at  `1L`, which is a very vendor-specific assumption.

If you instead use the ID value from the saved entity as returned by the `save(...)` method of the repository, your test should pass.

**Comment by paulvi** [comment]
This is however what is common for Hibernate and Spring current Getting started guides.
