### ISSUE TITLE
1.1.2 Support case: custom behavior to all repositories 

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#94]
It looks like custom implementation for base repository is not supported

While of cause this can't be mocked, the project should warn and ignore, but not fail

```
com.mmnaseri.utils.spring.data.error.DataOperationDefinitionException: Encountered an error while resolving operation metadata: public abstract java.util.List com.bee2c.platform.repository.ExtendedJpaRepository.findByCon(java.lang.String,java.util.Map)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.DefaultDataOperationResolver.resolve(DefaultDataOperationResolver.java:45)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getInvocationMappings(DefaultRepositoryFactory.java:210)
	at com.mmnaseri.utils.spring.data.proxy.impl.DefaultRepositoryFactory.getInstance(DefaultRepositoryFactory.java:76)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:103)
	at com.mmnaseri.utils.spring.data.dsl.mock.RepositoryMockBuilder.mock(RepositoryMockBuilder.java:101)
	at com.mmnaseri.utils.spring.data.dsl.factory.RepositoryFactoryBuilder.mock(RepositoryFactoryBuilder.java:273)
	at com.bee2c.platform.MbpDatabaseRelationsTestManual.testDemo(MbpDatabaseRelationsTestManual.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.mmnaseri.utils.spring.data.error.QueryParserException: interface com.bee2c.platform.repository.ExtendedJpaRepository: Could not find property `con` on `class com.bee2c.platform.entity.FbpMbpPolicy`
	at com.mmnaseri.utils.spring.data.domain.impl.MethodQueryDescriptionExtractor.getPropertyDescriptor(MethodQueryDescriptionExtractor.java:264)
	at com.mmnaseri.utils.spring.data.domain.impl.MethodQueryDescriptionExtractor.parseExpression(MethodQueryDescriptionExtractor.java:206)
	at com.mmnaseri.utils.spring.data.domain.impl.MethodQueryDescriptionExtractor.extract(MethodQueryDescriptionExtractor.java:134)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.QueryMethodDataOperationResolver.resolve(QueryMethodDataOperationResolver.java:53)
	at com.mmnaseri.utils.spring.data.proxy.impl.resolvers.DefaultDataOperationResolver.resolve(DefaultDataOperationResolver.java:43)
	... 29 more
Caused by: java.lang.IllegalStateException: Could not find property `con` on `class com.bee2c.platform.entity.FbpMbpPolicy`
	at com.mmnaseri.utils.spring.data.tools.PropertyUtils.getPropertyDescriptor(PropertyUtils.java:217)
	at com.mmnaseri.utils.spring.data.domain.impl.MethodQueryDescriptionExtractor.getPropertyDescriptor(MethodQueryDescriptionExtractor.java:262)
	... 33 more


```

http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-behaviour-for-all-repositories

```java
package com.bee2c.platform.repository;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.PagingAndSortingRepository;

@NoRepositoryBean
public interface ExtendedJpaRepository<T, ID extends Serializable> 
	extends PagingAndSortingRepository<T, ID> {

	public List<T> findByCon(String jpql, Map<String, Object> map);

	public List<T> findByCon(String jpql, Object... para);

}
```

```java
package com.bee2c.platform.repository;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.support.JpaEntityInformation;
import org.springframework.data.jpa.repository.support.SimpleJpaRepository;

/**
 * docs
 * http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#
 * repositories.custom-behaviour-for-all-repositories
 * 
 * @author Paul Verest
 *
 */
public class ExtendedJpaRepositoryImpl<T, ID extends Serializable> extends SimpleJpaRepository<T, ID>
		implements ExtendedJpaRepository<T, ID> {

	private final EntityManager em; 

	public ExtendedJpaRepositoryImpl(JpaEntityInformation entityInformation, EntityManager entityManager) {
		super(entityInformation, entityManager);

		// Keep the EntityManager around to be used from the newly introduced
		// methods.
		this.em = entityManager;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<T> findByCon(String jpql, Map<String, Object> map) {
		Query query = em.createQuery(jpql);
		for (String key : map.keySet()) {
			query.setParameter(key, map.get(key));
		}
		return query.getResultList();
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<T> findByCon(String jpql, Object... paras) {
		Query query = em.createQuery(jpql);
		for (int i = 0; i < paras.length; i++) {
			Object para = paras[i];
			query.setParameter(i + 1, para);
		}
		return query.getResultList();
	}
	
}

```

**Comment by mmnaseri** [comment]
You can specify a custom implementation for the repository factory configuration (which can be reused to mock multiple repositories) in this way:

    final RepositoryFactory factory = RepositoryFactoryBuilder.builder()
        .honoringImplementation(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
        .build();

which can then be used to instantiate repositories:

    final CustomerRepository repo = factory.getInstance(keyGenerator, CustomerRepository.class, Implementation1.class, Implementation2.class);

or, alternatively, to be more in keeping with the configuration DSL, you can do it this way:

    final RepositoryFactoryBuilder builder = RepositoryFactoryBuilder.builder()
        .honoringImplementation(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
        .and(SuperType.class, CustomImplementation.class)
    
and later:

    final CustomerRepository repo = builder.usingImplementation(CustomImplementation.class)
        .and(CustomImplementation.class)
        .mock(CustomerRepository.class);

This is safe to do because all the methods of the RepositoryFactoryBuilder class are stateless (right up to the point where you want to configure a call to the call to the `getInstance(...)`method of the RepositoryFactory. This means you can do this:

   final RepositoryFactoryBuilder builder1 = RepositoryFactoryBuilder.builder().honoringImplementation(Object.class, CustomImpl1.class);
    final RepositoryFactoryBuilder builder2 = builder1.and(Object.class, CustomImpl2.class);

and customizing `builder2` will not change `builder1` in any way.

**Comment by mmnaseri** [comment]
As of 8240c3d we can use `RepositoryFactoryBuilder.configure()` to get the underlying configuration object, like so:

````java
final RepositoryFactoryConfiguration configuration = RepositoryFactoryBuilder.builder()
    .honoringImplementation(SuperType.class, CustomImplementation.class)
    .and(SuperType.class, CustomImplementation.class)
    .and(SuperType.class, CustomImplementation.class)
    .and(SuperType.class, CustomImplementation.class)
    .configure();
````
It turns out that I had this feature planned and it was even referenced in the docs, but for some reason I had removed it.

**Comment by paulvi** [comment]
First I need some time to digest this all above.

Second, in the end the should be docs or samples to give example close to Spring Data docs.

My current summary is that

custom for all

```java
public interface BaseCustomJpaRepository
//	<T, ID extends Serializable> 
    extends PagingAndSortingRepository<T, ID> {

public class BaseCustomJpaRepositoryImpl<T, ID extends Serializable> extends SimpleJpaRepository<T, ID>
        implements ExtendedJpaRepository<T, ID> 
```
		
custom for one		

```java
public interface SomeRepositoryCustom

public class SomeRepositoryCustomImpl implements SomeRepositoryCustom
```


and finally 

```java
public interface SomeRepositoryCustom extends 
	BaseCustomJpaRepository<,>,
	SomeRepositoryCustom,
	//QueryByExampleExecutor<>,
	//JpaSpecificationExecutor<>,
	//QueryDslPredicateExecutor,
	{
```	

That is repository may be defined by up to 5 files: 2 for Base, 1 main interface, 2 files for custom methods.  
Note that documentation says that implementations MUST have `Impl` suffix

**Comment by mmnaseri** [comment]
I do not enforce the `Impl` suffix, since I cannot reuse the default implementations used by Spring anyway. But yes, you can do exactly that:

````java
final RepositoryConfiguration configuration = RepositoryFactoryBuilder.builder()
    .honoringImplementation(BaseCustomJpaRepository.class, BaseCustomJpaRepositoryImpl.class)
    .configure()
````

and later, on a per repository basis:

````java
final SomeRepository repository = new RepositoryMockBuilder()
    .usingConfiguration(configuration)
    .usingImplementation(SomeRepositoryCustomImpl.class)
    .mock(SomeRepository.class);
````

**Comment by paulvi** [comment]
well, the code is to be in a sample or docs. And your ideas are clearer with it.

**Comment by mmnaseri** [comment]
Yeah. I will need to do some serious work on samples. I haven't had much time to give it any love, but this is definitely a must.

**Comment by mmnaseri** [comment]
I am closing this as I have created a separate issue for defining better samples.

**Comment by mmnaseri** [comment]
I have to amend the above statement and mention that all methods of the builders exposed by the factory are stateless as of `1.1.3`

**Comment by paulvi** [comment]
Visualizing Spring and example objects for the case

![dataaccessstack](https://cloud.githubusercontent.com/assets/1614482/16102628/ea455944-33a3-11e6-9373-08e704a694cd.png)
